### PR TITLE
First draft of schema

### PR DESCRIPTION
**Pull request by uekerman**
Schema is certainly not yet ready. This is more to have sth to start from.

See also #18 

Try the MetaConfigurator like this:  https://metaconfigurator.github.io/meta-configurator/?schema=https://github.com/precice/preeco-orga/blob/add-schema-draftz/guidelines/adapter_schema.json&settings=https://github.com/precice/preeco-orga/blob/add-schema-draftz/guidelines/meta_configurator_settings.json

### CODE REVIEW

**Comment by MakisH** [comment]
Very nice linking to the MetaConfigurator as well, but shouldn't we document at least this part somewhere?

Should we maybe have these files in a separate directory `adapter-config-schema` with a `README.md` file explaining what this is about and linking to the MetaConfigurator?

Just think of the people that will end up on this file through a search engine.

**Comment by uekerman** [comment]
I now created a folder `adapter-config-schema` at the root of the repo. Is this what you had in mind?
Together with a README.

**Comment by MakisH** [comment]
> I now created a folder `adapter-config-schema` at the root of the repo. Is this what you had in mind? Together with a README.

Yes, exactly

**Review by MakisH — APPROVED** [review]
Good enough to be merged already. We will iterate on it soon.

**Pull request merged**
